server:
  port: 8080
spring:
  datasource:
    password: root
    url: jdbc:mysql://mysqldb:3306/eleventhproject
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
          
